services:
  mlflow-db:
    image: postgres:16
    container_name: mlflow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5433:5432"
    volumes:
      - mlflow_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: mlflow-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mlflow_minio:/data

  mlflow:
    image: python:3.11-slim
    container_name: mlflow-tracking
    restart: unless-stopped
    depends_on:
      - mlflow-db
      - minio
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    ports:
      - "5000:5000"
    command: >
      bash -lc "
      pip install --no-cache-dir mlflow==3.10.0 psycopg2-binary boto3 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@mlflow-db:5432/${PG_DB}
      --artifacts-destination s3://mlflow-artifacts
      --serve-artifacts
      "

volumes:
  mlflow_pgdata:
  mlflow_minio:
